# frozen_string_literal: true

require 'yaml'
require 'colorator'

desc 'Render the templated files'
task :render do
  sh '_scripts/render'
end

desc 'Optimize images in modified uncommitted files. For other images, use "path" such as "rake image_optim path=../path/to/dir/or/file".'
task :image_optim do
  puts
  puts 'Checking images ...'.magenta
  path = ENV['path']

  unless path
    puts 'Looking in uncommitted files ...'.blue
    modified_files = `git ls-files --modified --others --exclude-standard -- ..`.split("\n")
    deleted_files = `git ls-files --deleted -- ..`.split("\n")
    image_files_to_check = (modified_files - deleted_files).select do |file|
      File.extname(file) =~ /\.(png|jpg|jpeg|gif)/i
    end

    next puts 'No images to check.'.magenta if image_files_to_check.empty?

    path = image_files_to_check.join(' ')
  end

  system "bundle exec image_optim --recursive --no-svgo #{path}"
end

desc 'Generate an Azure regions map.
  Place the input data file in _jekyll/tmp/azure-regions.json.
  The result will be found in _jekyll/tmp/azure-regions.svg.
  Note, you need Python, PyGMT, and pdf2svg installed.'
task :azure_regions do
  puts 'Generating Azure regions map in PDF: $ '.magenta
  puts 'Note, you need python, pygmt, and pdf2svg installed.'.blue
  sh 'python _scripts/azure_regions.py'
  puts 'Converting PDF to SVG: $ '.magenta
  sh 'pdf2svg tmp/azure-regions.pdf tmp/azure-regions.svg'
end
